Support classic-flavored ingest keys
honeycombio/libhoney-rb pull request #138
Opened 2024-02-23 21:00 UTC by robbkidd

## Which problem is this PR solving?

There's a new key format on the block: ingest keys. To determine the correct dataset defaults for classic environments, the key detection logic needs an update. So that the details of the logic are implemented in fewer places, expose the logic as public methods, primarily for Beeline use. 

## Short description of the changes

- update classic key detection logic
- promote `Libhoney::Client.classic_write_key?` to public instance method
- also provide same logic as a module-level method `Libhoney.classic_write_key?` so the check can be made without an instance of the client

## To Consider

- Is the dated "write_key" vocabulary something we want to keep as this method goes public? Maybe provide aliased `classic_api_key?` methods as well?

2024-02-23 21:41 UTC, robbkidd commented on test/libhoney_test.rb
> +    classic_v3_ingest_key = 'hcaic_1234567890123456789012345678901234567890123456789012345678'
Or I could `SecureRandom.hex(58/2)` to get a 58-character string to add to the prefix. ¯\\\_(ツ)\_/¯

2024-02-23 21:45 UTC, jharley commented
> Is the dated "write_key" vocabulary something we want to keep as this method goes public?

This is a very thoughtful question, but, I think in libhoney land 'write key' is a deeply engrained so maybe not worth the modernization? Though, no harm in adding it :)

2024-02-23 21:45 UTC, jharley approved these changes
Looks great ✨

2024-02-26 09:40 UTC, MikeGoldsmith requested changes
I would prefer to see api_key replace write_key if we're making things public. It is an older term that we do not use outside of libhoney's. This isn't a function we anticipate external users to interact anyway with so happy to move towards conformity and reduce maintenance confusion.

2024-03-07 17:05 UTC, MikeGoldsmith approved these changes

2024-03-07 17:05 UTC, MikeGoldsmith commented on lib/libhoney/client.rb
>      def classic_write_key?(write_key)
Should this func be updated to `claassic_api_key` too?

2024-03-07 17:10 UTC, robbkidd commented on lib/libhoney/client.rb
>      def classic_write_key?(write_key)
It's not obvious from the diff, but this method is private. I left it named as is to minimize changes, but I'm happy to rename it, too, is service of consistency.

2024-03-07 17:13 UTC, MikeGoldsmith commented on lib/libhoney/client.rb
>      def classic_write_key?(write_key)
Yeah, let's go for consistency. It's a simple change but we'll likely forget to do it later 😄

2024-03-07 17:20 UTC, robbkidd commented on lib/libhoney/client.rb
>      def classic_write_key?(write_key)
Done in 2a1a1fe!

2024-03-07 17:26 UTC, merged