Process single-error responses from the Batch API
honeycombio/libhoney-rb pull request #89
Opened 2021-06-24 21:48 UTC by robbkidd

Fixes #86

2021-06-24 21:49 UTC, robbkidd commented on lib/libhoney/client.rb
> +    #   +host+ is required. +port+ is optional (default:80), unless a +username+ is included. +password+ is optional.
Uh. I'd been trying to make the layout of this RDoc less bad. Didn't mean to include it in this PR. I'll remove this.

2021-06-24 21:53 UTC, robbkidd commented on test/libhoney_test.rb
> +      # assert_equal([], responses.map(&:metadata))
oops. I'll get rid of this.

2021-07-08 00:15 UTC, vreynolds approved these changes

2021-07-08 00:15 UTC, vreynolds commented on lib/libhoney/transmission.rb
> +          enqueue_response(
minor nit: the two (create response)/enqueue branches are not symmetrical

2021-07-08 00:16 UTC, vreynolds commented
Needs bump label

2021-07-16 13:18 UTC, MikeGoldsmith requested changes
@robbkidd - there's a couple of TODOs and feedback to fix up before we can merged this.

2021-07-19 17:58 UTC, robbkidd commented on lib/libhoney/transmission.rb
> +          enqueue_response(
Updated so that the two sides of the branch use `enqueue_response( Response.new( ... ) )` for more matchy matchy.

2021-07-19 18:20 UTC, vreynolds approved these changes

2021-07-19 19:09 UTC, merged